
server:
  port: 8085  


  

management:
  endpoints:
    web:
      exposure:
        include: health,info
 # (use 8083 for consumption-service)

spring:
  application:
    name: realtime-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/smart_energy_demo
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect